### ISSUE TITLE
System.AccessViolationException: Attempted to read or write protected memory.

### ISSUE THREAD

**Issue by momscoder** [spvessel/spacevil#10]
SpaceVIL version: 0.3.6.0-ALPHA - June 2020
Platform: .Net Core
OS type: Linux
OS: Arch Linux (KDE)

Open Kate -> Copy Text -> Close Kate -> Paste Text in TextEdit-> Exception

How to catch it?

Unhandled exception. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadByte(IntPtr ptr, Int32 ofs)
   at A.b.A(IntPtr )
   at A.b.f(Int64 )
   at SpaceVIL.Common.CommonService.GetClipboardString()
   at A.N.A(ITextShortcuts , KeyArgs )
   at B.W.a(Object , KeyArgs )
   at A.g.A(Int64 , KeyCode , Int32 , InputState , KeyMods )
   at A.e.A(Int64 , KeyCode , Int32 , InputState , KeyMods )
   at A.b.A(Double )
   at SpaceVIL.WindowManager.A.b()
   at SpaceVIL.WindowManager.b()
   at A.o.D()
   at SpaceVIL.CoreWindow.Show()

P.S. sorry if this is not a library problem

**Comment by spvessel** [comment]
Ok, I'll try to find out more about this. As I understand it, you copy (CTRL + C) some text from Kate (a text editor?), Then close the Kate app and try to paste (CTRL + V) the text into SpaceVIL.TextEdit?

**Comment by momscoder** [comment]
> Ok, I'll try to find out more about this. As I understand it, you copy (CTRL + C) some text from Kate (a text editor?), then close the Kate app and try to paste (CTRL + V) the text into SpaceVIL.TextEdit?
> PS. Everything works fine in Windows 10.

Will i continue in Russian?

Да, Kate - это текстовый редактор, и цепочка как вы и описали. Я уверен, что это проблема Kate, но нельзя сделать например событие, или просто игнорировать и не вставлять текст? Просто программа крашится из-за такой мелочи

**Comment by spvessel** [comment]
Я сейчас тестю на убунте. А это только с Kate такая штука происходит или всегда?

**Comment by momscoder** [comment]
Нигде кроме Kate не тестил

**Comment by momscoder** [comment]
> Нигде кроме Kate не тестил

поробовал в notepadqq, всё то же самое

**Comment by momscoder** [comment]
а ещё обнаружил, что если запускать с русской раскладкой клавиатуры, то backspace не работает

**Comment by spvessel** [comment]
А если не закрывать то работает ли так же?

**Comment by momscoder** [comment]
> А если не закрывать то работает или так же?

Если не закрывать, то работает

**Comment by spvessel** [comment]
Ага, это видимо баг данного линукса. Это можно исправить, ща посмотрю в чем проблема с backspace'ом, скомпилирую и дам ссылку на новый билд, ок?

**Comment by momscoder** [comment]
> Ага, это видимо баг данного линукса. Это можно исправить, ща посмотрю в чем проблема с backspace'ом, скомпилирую и дам ссылку на новый билд, ок?

Ок, но не факт, что я смогу проверить, т.к. вынужден отъехать из дома

**Comment by spvessel** [comment]
Ну как будет время)

**Comment by momscoder** [comment]
> Ну как будет время)

Да, спасибо

**Comment by spvessel** [comment]
Вот для NetCore:
https://spvessel.com/spacevil/downloads/momscoder/spacevil_dotnet_core_0.3.6.0-momscoder.zip
PS. С backspace нужно больше разбираться, походу это глюк то ли линуксов, то ли самого glfw (java версия фреймворка работает в этом плане нормально)

**Comment by momscoder** [comment]
> Вот для NetCore:
> https://spvessel.com/spacevil/downloads/momscoder/spacevil_dotnet_core_0.3.6.0-momscoder.zip
а что конкретно вы сделали? у меня не работает, но может я что не так делаю \:

**Comment by spvessel** [comment]
Хм, вообще должно было сработать. Ладно я еще кое что попробую и скажу когда перекачать новую версию.

**Comment by momscoder** [comment]
> Хм, вообще должно было сработать. Ладно я еще кое что попробую и скажу когда перекачать новую версию.
> Просто обработал исключение, при возникновении должно было проигнорировать команду вставки.

Ошибка приходит из метода Show(), может это поможет

**Comment by spvessel** [comment]
Мой косяк, не ту версию положил. Перекачай:
https://spvessel.com/spacevil/downloads/momscoder/spacevil_dotnet_core_0.3.6.1_momscoder.zip

**Comment by momscoder** [comment]
Отлично, всё работает!
