### ISSUE TITLE
Impossible to run any example

### ISSUE THREAD

**Issue by Guddiny** [spvessel/spacevil#3]
Every time when i try to run some example i get exception:
![image](https://user-images.githubusercontent.com/16209082/66189031-7b9c5480-e691-11e9-9aff-269ac234a0d0.png)

**Comment by Maobuff** [comment]
First of all: rename glfw3.dll to glfw 
(ATTENTION FOR WINDOWS OS USERS:
GLFW library should be renamed to "glfw.dll" (if you download binaries from the official GLFW website, you get a library named "glfw3.dll")
 And most important update .net to latest version (4.7.something)

**Comment by Guddiny** [comment]
![image](https://user-images.githubusercontent.com/16209082/66189566-af2bae80-e692-11e9-87c3-a4e93c892dbf.png)

**Comment by Guddiny** [comment]
The problem solved - jsut PC reboot.Thanks!
